/**
 * @fileoverview
 *   remark preset to configure `remark-lint` with settings that prevent
 *   mistakes or syntaxes that do not work correctly across vendors.
 */

'use strict'

module.exports.plugins = [
    [require('remark-lint'), ['error']],
    [require('remark-lint-blockquote-indentation'), ['error']],
    [require('remark-lint-checkbox-character-style'), ['error']],
    [require('remark-lint-checkbox-content-indent'), ['error']],
    [require('remark-lint-code-block-style'), ['error']],
    [require('remark-lint-definition-case'), ['error']],
    [require('remark-lint-definition-spacing'), ['error']],
    [require('remark-lint-emphasis-marker'), ['error']],
    [require('remark-lint-fenced-code-flag'), ['error']],
    [require('remark-lint-fenced-code-marker'), ['error']],
    [require('remark-lint-file-extension'), ['error']],
    [require('remark-lint-final-definition'), ['error']],
    [require('remark-lint-final-newline'), ['error']],
    [require('remark-lint-first-heading-level'), ['error']],
    [require('remark-lint-hard-break-spaces'), ['error']],
    [require('remark-lint-heading-increment'), ['error']],
    [require('remark-lint-heading-style'), ['error']],
    [require('remark-lint-linebreak-style'), ['error']],
    [require('remark-lint-link-title-style'), ['error']],
    [require('remark-lint-list-item-bullet-indent'), ['error']],
    [require('remark-lint-list-item-content-indent'), ['error']],
    [require('remark-lint-list-item-indent'), ['error']],
    [require('remark-lint-list-item-spacing'), ['error']],
    [require('remark-lint-maximum-heading-length'), ['error']],
    [require('remark-lint-maximum-line-length'), ['error']],
    [require('remark-lint-no-auto-link-without-protocol'), ['error']],
    [require('remark-lint-no-blockquote-without-marker'), ['error']],
    [require('remark-lint-no-consecutive-blank-lines'), ['error']],
    [require('remark-lint-no-duplicate-definitions'), ['error']],
    [require('remark-lint-no-duplicate-headings'), ['error']],
    [require('remark-lint-no-duplicate-headings-in-section'), ['error']],
    [require('remark-lint-no-emphasis-as-heading'), ['error']],
    [require('remark-lint-no-empty-url'), ['error']],
    [require('remark-lint-no-file-name-articles'), ['error']],
    [require('remark-lint-no-file-name-consecutive-dashes'), ['error']],
    [require('remark-lint-no-file-name-irregular-characters'), ['error']],
    [require('remark-lint-no-file-name-mixed-case'), ['error']],
    [require('remark-lint-no-file-name-outer-dashes'), ['error']],
    [require('remark-lint-no-heading-content-indent'), ['error']],
    [require('remark-lint-no-heading-indent'), ['error']],
    [require('remark-lint-no-heading-like-paragraph'), ['error']],
    [require('remark-lint-no-heading-punctuation'), ['error']],
    [require('remark-lint-no-html'), ['error']],
    [require('remark-lint-no-inline-padding'), ['error']],
    [require('remark-lint-no-literal-urls'), ['error']],
    [require('remark-lint-no-missing-blank-lines'), ['error']],
    [require('remark-lint-no-multiple-toplevel-headings'), ['error']],
    [require('remark-lint-no-paragraph-content-indent'), ['error']],
    [require('remark-lint-no-reference-like-url'), ['error']],
    [require('remark-lint-no-shell-dollars'), ['error']],
    [require('remark-lint-no-shortcut-reference-image'), ['error']],
    [require('remark-lint-no-shortcut-reference-link'), ['error']],
    [require('remark-lint-no-table-indentation'), ['error']],
    [require('remark-lint-no-tabs'), ['error']],
    [require('remark-lint-no-undefined-references'), ['error']],
    [require('remark-lint-no-unneeded-full-reference-image'), ['error']],
    [require('remark-lint-no-unneeded-full-reference-link'), ['error']],
    [require('remark-lint-no-unused-definitions'), ['error']],
    [require('remark-lint-ordered-list-marker-style'), ['error']],
    [require('remark-lint-ordered-list-marker-value'), ['error']],
    [require('remark-lint-rule-style'), ['error']],
    [require('remark-lint-strong-marker'), ['error']],
    [require('remark-lint-table-cell-padding'), ['error']],
    [require('remark-lint-table-pipe-alignment'), ['error']],
    [require('remark-lint-table-pipes'), ['error']],
    [require('remark-lint-unordered-list-marker-style'), ['error']]
]
